*

diff --git a/bin/puavo-img-tool b/bin/puavo-img-tool
--- a/bin/puavo-img-tool
+++ b/bin/puavo-img-tool
@@ -1,14 +1,21 @@
 #!/bin/sh
 
-CLASS_O=""
-DIST_O=""
-OSNAME_O=""
+#pwd
+
+if test -f ./bin/config.class;then CLASS_O=$(cat ./bin/config.class);else CLASS_O="";fi
+if test -f ./bin/config.dist;then DIST_O=$(cat ./bin/config.dist);else DIST_O="";fi
+if test -f ./bin/config.osname;then OSNAME_O=$(cat ./bin/config.osname);else OSNAME_O="";fi
+if test -f ./bin/config.source;then SOURCE_O=$(cat ./bin/config.source);else SOURCE_O="";fi
+if test -f ./bin/config.datadir;then DATA_O=$(cat ./bin/config.datadir);else DATA_O="";fi
+					  
+
 INTER_O="1"
 FORCE_O="1"
 
-DATAPATH=""
+CONFIG_O="1"
 
-echo $@
+
+#echo $@
 
 while [ $# -gt 0 ]; do
     case $1 in
@@ -18,31 +25,51 @@ while [ $# -gt 0 ]; do
 	    echo
 	    echo "Patch a PuavoOS imagec and (eventualy) compress a new image." 
 	    echo
-	    echo "Options:"
- 	    echo "    -o, --osname OSNAME        set image osname (defaults to source osname)"
-	    echo "    -c, --class CLASS          set image class (defaults to source class)"
-	    echo "    -d, --datadir DATAPATH     copies datadir to chroot"
+	    echo "Config options:"
+	    echo "    -s, --source SOURCE        set source to SOURCE ($SOURCE_O)"
+	    echo "    -d, --datadir DATADIR      set datadir to DATADIR ($DATA_O)"
+ 	    echo "    -o, --osname OSNAME        set image osname ($OSNAME_O)"
+	    echo "    -c, --class CLASS          set image class ($CLASS_O)"
+            echo
+	    echo "Runtime options:"
  	    echo "    -i, --interactice          force interactive shell"
  	    echo "    -f, --force                force building image even with errors"
  	    echo "    -h, --help                 show this help"
 	    echo
 	    exit 0
 	    ;;
+
+	#config 
+	-s|--source)
+	    shift
+	    SOURCE_O=$1
+	    CONFIG_O=0
+	    echo $1 > ./bin/config.source
+	    shift
+	    ;;
 	-c|--class)
 	    shift
 	    CLASS_O=$1
+	    CONFIG_O=0
+	    echo $1 > ./bin/config.class
 	    shift
 	    ;;
 	-o|--osname)
 	    shift
 	    OSNAME_O=$1
+	    CONFIG_O=0
+	    echo $1 > ./bin/config.osname
 	    shift
 	    ;;
 	-d|--datadir)
 	    shift
-	    DATAPATH=$1
+	    DATA_O=$1
+	    CONFIG_O=0
+	    echo $1 > ./bin/config.datadir
 	    shift
 	    ;;
+
+	#runtime
 	-i|--interactive)
 	    shift
 	    INTER_O="0"
@@ -65,40 +92,62 @@ while [ $# -gt 0 ]; do
     esac
 done
 
-echo $@
+if test $CONFIG_O = 0;then
+    echo "info: config set. exiting ..."
+    exit 0
+fi
 
-if [ $# -ne 1 ]; then
-    echo  "error: invalid number of arguments ($#), expected 1"
-    exit 1
+echo "info: starting process ..."
+
+
+echo "----> $@"
+
+if [ $# -eq 1 ]; then
+    SOURCE_O=$1
+    INTER_O=0
 fi
 
 
-SOURCE=$1
 
 #check source image
-if test -h $SOURCE;then
-    ANS="$(readlink -e $SOURCE)"
+if test -z "$SOURCE_O";then
+    echo "error: source param not set"
+    exit 1
+fi
+if test -h $SOURCE_O;then
+    ANS="$(readlink -e $SOURCE_O)"
     if ! test -n "$ANS";then
-	echo "error: link not ok"
+	echo "error: source link not ok"
 	exit 1
     fi
 else
-    if ! test -e $SOURCE;then
-	echo "error: file not found"
+    if ! test -e $SOURCE_O;then
+	echo "error: source file not found"
 	exit 1
     fi	
 fi
 
 #check datadir
-if test -n "$DATAPATH";then
-    if ! test -d $DATAPATH;then
+if test -n "$DATA_O";then
+    if ! test -d $DATA_O;then
         echo "error: datadir not found"
         exit 1
     fi
+else
+    echo "error: datadir not set"
+    exit 1
 fi
 
+
+
+echo "info: params ok"
+
+
 #mount image
-puavo-img-mount $SOURCE
+SOURCE=$SOURCE_O
+DATAPATH=$DATA_O
+
+sudo puavo-img-mount $SOURCE
 
 
 CHROOT=$(basename -s .img $SOURCE)
@@ -107,7 +156,7 @@ if test -e $CHROOT/etc/puavo-image/name;then
     NAME=$(cat $CHROOT/etc/puavo-image/name)
 else
     echo "error: $CHROOT does not seem to be a puavo-os image"
-    puavo-img-mount --umount $SOURCE
+    sudo puavo-img-mount --umount $SOURCE
     exit 1
 fi
 
@@ -122,26 +171,12 @@ else
     OSNAME=$OSNAME_I
 fi
 
-if test -n "$SERIE_O";then
-    SERIE=$SERIE_O
-else
-    SERIE=$SERIE_I
-fi
-
 if test -n "$CLASS_O";then
     CLASS=$CLASS_O
 else
     CLASS=$CLASS_I
 fi
 
-if test -d $DATAPATH/bin.d/ -o -d $DATAPATH/files.d -o -d $DATAPATH/debs.d -o -d $DATAPATH/lists.d -o -d $DATAPATH/parts.d;then
-    INTERACTIVE=1
-else
-    INTERACTIVE=0
-fi
-if test "$INTER_O" = "0";then
-    INTERACTIVE=0
-fi
 
 
 #copy data to image
@@ -166,6 +201,7 @@ if test -d /install/bin.d;then
         echo "**************************************************************"
         for B in $(ls /install/bin.d);do
 	    if test -x /install/bin.d/$B;then
+                echo $B
 		/install/bin.d/$B
 		if test $? = 1;then ERROR=1;fi
 	    fi 
@@ -181,7 +217,7 @@ if test -d /install/files.d;then
         echo "**************************************************************"
         cp -r /install/files.d/* /
 	if test $? = 1;then ERROR=1;fi
-        echo "ok"
+        echo "done"
     fi
 fi
 
@@ -198,6 +234,7 @@ if test -d /install/lists.d;then
         apt-get -y install $(cat /install/lists.d/*list|xargs)
 	if test $? = 1;then ERROR=1;fi
     fi
+    echo "done"
 fi
 
 #debs
@@ -207,6 +244,7 @@ if test -d /install/debs;then
         echo "                         debs                                *"
         echo "**************************************************************"
         for D in $(ls /install/debs/*.deb);do
+             echo $D
              dpkg -i $D
              #if test $? = 1;then ERROR=1;fi
         done
@@ -231,6 +269,7 @@ if test -d /install/parts.d;then
 	fi
         for P in $(ls /install/parts.d/);do
             if test -x /install/parts.d/$P/install.sh;then
+                 echo $P
                  /install/parts.d/$P/install.sh
   	         if test $? = 1;then ERROR=1;fi
             fi
@@ -261,19 +300,20 @@ fi
 if ! test -d $CHROOT/install/;then
     mkdir -p $CHROOT/install/
 fi
+echo "copy data to chroot"
 cp -r  $DATAPATH/* $CHROOT/install/
 
 #patch!
-if test $INTERACTIVE = 1;then
-    #echo "non interactive"
+if test $INTER_O = 1;then
+    echo "non interactive"
     echo "/usr/local/bin/puavo-chroot-apply" | puavo-dir-chroot $CHROOT
 else
-    #echo "interactive"
+    echo "interactive"
     puavo-dir-chroot $CHROOT
 fi
 
 
-if test $? = 0 -o FORCE_O = 0;then
+if test $? = 0 -o $FORCE_O = 0;then
 #    cache debs
      rsync -rav  --delete --size-only  $CHROOT/var/cache/apt/archives/ cache/apt/
 
