cleanup code

diff --git a/puavo-image-utils-0.1/usr/sbin/puavo-img-live b/puavo-image-utils-0.1/usr/sbin/puavo-img-live
--- a/puavo-image-utils-0.1/usr/sbin/puavo-img-live
+++ b/puavo-image-utils-0.1/usr/sbin/puavo-img-live
@@ -1,22 +1,25 @@
 #!/bin/sh
 
+if test -z "$1" -o "$1" = "-h" -o "$1" = "--help";then
+    echo "usage: puavo-img-live  IMAGE.img"
+    echo
+    echo "       Opens IMAGE.img in qemu for inspection."
+    echo "       When the qemu image does not exist, it"
+    echo "       will be build."
+    exit 0
+fi
 
-if test -z "$1";then
-    echo "usage: puavo-img-live IMAGE.img"
+
+IMAGE="$1"
+if ! test -f $IMAGE;then
+    echo "error: IMAGE \"$IMAGE\" not found"
     exit 1
 fi
-if ! test -f $1;then
-    echo "error: image $1 not found"
-    exit 1
-fi
 
-IMAGE=$1
 INSTALLER=$(basename -s .img $IMAGE)-inst.img
-
 
 if ! test -f $INSTALLER;then
     puavo-img-installer $IMAGE $INSTALLER
 fi
-
 
 qemu-system-x86_64  -enable-kvm -m 2G -hda $INSTALLER
diff --git a/puavo-image-utils-0.1/usr/sbin/puavo-img-repo b/puavo-image-utils-0.1/usr/sbin/puavo-img-repo
--- a/puavo-image-utils-0.1/usr/sbin/puavo-img-repo
+++ b/puavo-image-utils-0.1/usr/sbin/puavo-img-repo
@@ -1,7 +1,38 @@
 #!/bin/sh
 
-IMAGE_DIR="$(pwd)"
-MIRROR_DIR="$IMAGE_DIR/mirror"
+if test -z "$1" -o "$1" = "-h" -o "$1" = "--help";then
+    echo "usage: puavo-img-repo  IMAGE_DIR [MIRROR_DIR]"
+    echo
+    echo "       Maintains an image repository of all images from IMAGE_DIR"
+    echo "       in MIRROR_DIR. When MIRROR_DIR is not set it defaults to"
+    echo "       IMAGE_DIR/mirror ."
+    exit 0
+fi
+
+
+IMAGE_DIR="$1"
+if ! test -d $IMAGE_DIR;then
+    echo "error: IMAGEDIR \"$IMAGE_DIR\" not found"
+    exit 1
+fi
+if echo $IMAGE_DIR|grep -vq "^/.*";then
+    IMAGE_DIR="$(pwd)/$IMAGE_DIR"
+fi
+
+#echo $IMAGE_DIR
+
+if test -z "$2";then
+    MIRROR_DIR="$IMAGE_DIR/mirror"
+else
+    MIRROR_DIR=$2
+fi
+if echo $MIRROR_DIR|grep -vq "^/.*";then
+    MIRROR_DIR="$(pwd)/$MIRROR_DIR"
+fi
+
+
+#echo $MIRROR_DIR
+
 
 
 list_images(){
@@ -57,15 +88,18 @@ test -d $MIRROR_DIR/meta || mkdir -p $MIRROR_DIR/meta
 test -d $MIRROR_DIR/rdiffs || mkdir -p $MIRROR_DIR/rdiffs
 cd ${IMAGE_DIR}/.puavo-os
 
+
+#needs absolute paths!!!!!!!!!!!!
 sudo /puavo-os/.aux/make-rdiffs \
         image_dir="${IMAGE_DIR}" \
 	images_urlbase="https://cdn.puavo.org" \
 	mirror_dir="${MIRROR_DIR}" \
 	mode="production" 
 
+
 # fix permissions
-sudo chown --recursive --reference ${IMAGE_DIR} ${IMAGE_DIR}/.puavo-os
-sudo chown --recursive --reference ${IMAGE_DIR} ${MIRROR_DIR}
+sudo chown --recursive --reference ${IMAGE_DIR}  ${IMAGE_DIR}/.puavo-os
+sudo chown --recursive --reference ${IMAGE_DIR}  ${MIRROR_DIR}
 
 exit
 
